name: CI/CD Pipeline - DevOps Static Site

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: devopsacr707
  IMAGE_NAME: devops-static-site

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Tag Docker image for ACR
        run: docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image to ACR
        run: docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group devops-rg --name devops-aks --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl create deployment devops-static-site --image=${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest --dry-run=client -o yaml | kubectl apply -f -
          kubectl expose deployment devops-static-site --type=LoadBalancer --port=80 --target-port=80 --dry-run=client -o yaml | kubectl apply -f -
